const ACTION_AUTH_LOGIN = 'ACTION_AUTH_LOGIN'
const ACTION_AUTH_LOGOUT = 'ACTION_AUTH_LOGOUT'
const ACTION_GET_ALL_OWNED_WALLETS = 'ACTION_GET_ALL_OWNED_WALLETS'
const MUTATION_SET_OWNED_WALLETS = 'MUTATION_SET_OWNED_WALLETS'

export {
  ACTION_AUTH_LOGIN,
  ACTION_AUTH_LOGOUT,
  ACTION_GET_ALL_OWNED_WALLETS,
  MUTATION_SET_OWNED_WALLETS
}
